### ISSUE TITLE
cflinuxfs2 - showing error

### ISSUE THREAD

**Issue by killer-imaniac** [cloudfoundry/buildpack-packager#16]
The manifest does not conform to the schema:
': invalid 0 value.yml:19:3 [/dependencies/0/cf_stacks/0] 'cflinuxfs2

Manifest File:
---
language: go

url_to_dependency_map:
- match: go-(\d+\.\d+\.\d+)
  name: go
  version: $1

default_versions:
- name: go
  version: 1.5.4

dependencies:
- name: go
  version: 1.5.4
  uri: https://storage.googleapis.com/golang/go1.5.4.linux-amd64.tar.gz
  md5: 27b1c469797292064c65c995ffe30386
  cf_stacks:
  - cflinuxfs2

exclude_files:
  - .gitignore
  - private.key

**Comment by sclevine** [comment]
Hi @killer-imaniac,

I'm not sure what your question is. Can you provide more details? What command are you running, and what output do you see?

**Comment by killer-imaniac** [comment]
Hi @sclevine,
Command I ran was:
$ bundle install 
$ buildpack-packager --uncached

After the second command, it is showing error:

The manifest does not conform to the schema:
': invalid 0 value.yml:19:3 [/dependencies/0/cf_stacks/0] 'cflinuxfs2


I have also provided the manifest file I am using.

**Comment by sclevine** [comment]
Works for me with the latest version of buildpack-packager:
```
liberty:buildpack-packager-16 pivotal$ cat Gemfile
# frozen_string_literal: true
source "https://rubygems.org"
gem 'buildpack-packager', git: 'https://github.com/cloudfoundry-incubator/buildpack-packager'
liberty:buildpack-packager-16 pivotal$ cat manifest.yml
---
language: go

url_to_dependency_map:
- match: go-(\d+\.\d+\.\d+)
  name: go
  version: $1

default_versions:
- name: go
  version: 1.5.4

dependencies:
- name: go
  version: 1.5.4
  uri: https://storage.googleapis.com/golang/go1.5.4.linux-amd64.tar.gz
  md5: 27b1c469797292064c65c995ffe30386
  cf_stacks:
  - cflinuxfs2

exclude_files:
  - .gitignore
  - private.key
liberty:buildpack-packager-16 pivotal$ bundle exec buildpack-packager --uncached
Uncached buildpack created and saved as /Users/pivotal/workspace/buildpacks/issues/buildpack-packager-16/go_buildpack-v0.0.1.zip with a size of 4.0K
```
It's worth noting that this repo (along with compile-extensions) will soon be deprecated in favor of [libbuildpack](https://github.com/cloudfoundry/libbuildpack).
